//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirius.Client.Win32.Core.Menu
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://classes.win32.server.sirius.org/", ConfigurationName="Sirius.Client.Win32.Core.Menu.Menu")]
    public interface Menu
    {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/GetMenuItemRectRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/GetMenuItemRectResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.GetMenuItemRectResponse GetMenuItemRect(Sirius.Client.Win32.Core.Menu.GetMenuItemRectRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/GetMenuDefaultItemRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/GetMenuDefaultItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.GetMenuDefaultItemResponse GetMenuDefaultItem(Sirius.Client.Win32.Core.Menu.GetMenuDefaultItemRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/GetMenuItemCountRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/GetMenuItemCountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.GetMenuItemCountResponse GetMenuItemCount(Sirius.Client.Win32.Core.Menu.GetMenuItemCountRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/GetMenuItemIDRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/GetMenuItemIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.GetMenuItemIDResponse GetMenuItemID(Sirius.Client.Win32.Core.Menu.GetMenuItemIDRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/GetMenuItemInfoRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/GetMenuItemInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.GetMenuItemInfoResponse GetMenuItemInfo(Sirius.Client.Win32.Core.Menu.GetMenuItemInfoRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/GetMenuStringRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/GetMenuStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.GetMenuStringResponse GetMenuString(Sirius.Client.Win32.Core.Menu.GetMenuStringRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/IsMenuRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/IsMenuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.IsMenuResponse IsMenu(Sirius.Client.Win32.Core.Menu.IsMenuRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/GetMenuInfoRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/GetMenuInfoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.GetMenuInfoResponse GetMenuInfo(Sirius.Client.Win32.Core.Menu.GetMenuInfoRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/GetMenuStateRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/GetMenuStateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.GetMenuStateResponse GetMenuState(Sirius.Client.Win32.Core.Menu.GetMenuStateRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/GetSubMenuRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/GetSubMenuResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.GetSubMenuResponse GetSubMenu(Sirius.Client.Win32.Core.Menu.GetSubMenuRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://classes.win32.server.sirius.org/Menu/pickItemRequest", ReplyAction="http://classes.win32.server.sirius.org/Menu/pickItemResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(pointerType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(structure))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Menu.pickItemResponse pickItem(Sirius.Client.Win32.Core.Menu.pickItemRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class rect : structure
    {
        
        private int leftField;
        
        private int topField;
        
        private int rightField;
        
        private int bottomField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int left
        {
            get
            {
                return this.leftField;
            }
            set
            {
                this.leftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int top
        {
            get
            {
                return this.topField;
            }
            set
            {
                this.topField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int right
        {
            get
            {
                return this.rightField;
            }
            set
            {
                this.rightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int bottom
        {
            get
            {
                return this.bottomField;
            }
            set
            {
                this.bottomField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(menuinfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(rect))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(menuiteminfo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public abstract partial class structure
    {
        
        private bool autoReadField;
        
        private bool autoWriteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool autoRead
        {
            get
            {
                return this.autoReadField;
            }
            set
            {
                this.autoReadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool autoWrite
        {
            get
            {
                return this.autoWriteField;
            }
            set
            {
                this.autoWriteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class pointer
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(handle))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hbrush))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hbitmap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hmenu))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public abstract partial class pointerType
    {
        
        private pointer pointerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public pointer pointer
        {
            get
            {
                return this.pointerField;
            }
            set
            {
                this.pointerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hbrush))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hbitmap))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hmenu))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class handle : pointerType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class hbrush : handle
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class hbitmap : handle
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class hmenu : handle
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(integerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ulongPTR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dword))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@uint))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public abstract partial class number
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ulongPTR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dword))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@uint))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public abstract partial class integerType : number
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class ulongPTR : integerType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@uint))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class dword : integerType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class @uint : dword
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class menuinfo : structure
    {
        
        private int cbSizeField;
        
        private dword fMaskField;
        
        private dword dwStyleField;
        
        private @uint cyMaxField;
        
        private hbrush hbrBackField;
        
        private dword dwContextHelpIDField;
        
        private ulongPTR dwMenuDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cbSize
        {
            get
            {
                return this.cbSizeField;
            }
            set
            {
                this.cbSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public dword fMask
        {
            get
            {
                return this.fMaskField;
            }
            set
            {
                this.fMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public dword dwStyle
        {
            get
            {
                return this.dwStyleField;
            }
            set
            {
                this.dwStyleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public @uint cyMax
        {
            get
            {
                return this.cyMaxField;
            }
            set
            {
                this.cyMaxField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public hbrush hbrBack
        {
            get
            {
                return this.hbrBackField;
            }
            set
            {
                this.hbrBackField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public dword dwContextHelpID
        {
            get
            {
                return this.dwContextHelpIDField;
            }
            set
            {
                this.dwContextHelpIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public ulongPTR dwMenuData
        {
            get
            {
                return this.dwMenuDataField;
            }
            set
            {
                this.dwMenuDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://classes.win32.server.sirius.org/")]
    public partial class menuiteminfo : structure
    {
        
        private int cbSizeField;
        
        private @uint fMaskField;
        
        private @uint fTypeField;
        
        private @uint fStateField;
        
        private @uint wIDField;
        
        private hmenu hSubMenuField;
        
        private hbitmap hbmpCheckedField;
        
        private hbitmap hbmpUncheckedField;
        
        private ulongPTR dwItemDataField;
        
        private string dwTypeDataField;
        
        private @uint cchField;
        
        private hbitmap hbmpItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cbSize
        {
            get
            {
                return this.cbSizeField;
            }
            set
            {
                this.cbSizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public @uint fMask
        {
            get
            {
                return this.fMaskField;
            }
            set
            {
                this.fMaskField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public @uint fType
        {
            get
            {
                return this.fTypeField;
            }
            set
            {
                this.fTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public @uint fState
        {
            get
            {
                return this.fStateField;
            }
            set
            {
                this.fStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public @uint wID
        {
            get
            {
                return this.wIDField;
            }
            set
            {
                this.wIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public hmenu hSubMenu
        {
            get
            {
                return this.hSubMenuField;
            }
            set
            {
                this.hSubMenuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public hbitmap hbmpChecked
        {
            get
            {
                return this.hbmpCheckedField;
            }
            set
            {
                this.hbmpCheckedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public hbitmap hbmpUnchecked
        {
            get
            {
                return this.hbmpUncheckedField;
            }
            set
            {
                this.hbmpUncheckedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public ulongPTR dwItemData
        {
            get
            {
                return this.dwItemDataField;
            }
            set
            {
                this.dwItemDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string dwTypeData
        {
            get
            {
                return this.dwTypeDataField;
            }
            set
            {
                this.dwTypeDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public @uint cch
        {
            get
            {
                return this.cchField;
            }
            set
            {
                this.cchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public hbitmap hbmpItem
        {
            get
            {
                return this.hbmpItemField;
            }
            set
            {
                this.hbmpItemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemRect", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuItemRectRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sirius.Client.Win32.Core.Menu.rect arg3;
        
        public GetMenuItemRectRequest()
        {
        }
        
        public GetMenuItemRectRequest(long arg0, long arg1, int arg2, Sirius.Client.Win32.Core.Menu.rect arg3)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemRectResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuItemRectResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public GetMenuItemRectResponse()
        {
        }
        
        public GetMenuItemRectResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuDefaultItem", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuDefaultItemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public GetMenuDefaultItemRequest()
        {
        }
        
        public GetMenuDefaultItemRequest(long arg0, int arg1, int arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuDefaultItemResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuDefaultItemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetMenuDefaultItemResponse()
        {
        }
        
        public GetMenuDefaultItemResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemCount", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuItemCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public GetMenuItemCountRequest()
        {
        }
        
        public GetMenuItemCountRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemCountResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuItemCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetMenuItemCountResponse()
        {
        }
        
        public GetMenuItemCountResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemID", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuItemIDRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public GetMenuItemIDRequest()
        {
        }
        
        public GetMenuItemIDRequest(long arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemIDResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuItemIDResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetMenuItemIDResponse()
        {
        }
        
        public GetMenuItemIDResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemInfo", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuItemInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sirius.Client.Win32.Core.Menu.menuiteminfo arg3;
        
        public GetMenuItemInfoRequest()
        {
        }
        
        public GetMenuItemInfoRequest(long arg0, int arg1, bool arg2, Sirius.Client.Win32.Core.Menu.menuiteminfo arg3)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuItemInfoResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuItemInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public GetMenuItemInfoResponse()
        {
        }
        
        public GetMenuItemInfoResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuString", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("arg2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<ushort>[] arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg4;
        
        public GetMenuStringRequest()
        {
        }
        
        public GetMenuStringRequest(long arg0, int arg1, System.Nullable<ushort>[] arg2, int arg3, int arg4)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuStringResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetMenuStringResponse()
        {
        }
        
        public GetMenuStringResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsMenu", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class IsMenuRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public IsMenuRequest()
        {
        }
        
        public IsMenuRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="IsMenuResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class IsMenuResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public IsMenuResponse()
        {
        }
        
        public IsMenuResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuInfo", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuInfoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sirius.Client.Win32.Core.Menu.menuinfo arg1;
        
        public GetMenuInfoRequest()
        {
        }
        
        public GetMenuInfoRequest(long arg0, Sirius.Client.Win32.Core.Menu.menuinfo arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuInfoResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public GetMenuInfoResponse()
        {
        }
        
        public GetMenuInfoResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuState", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuStateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public GetMenuStateRequest()
        {
        }
        
        public GetMenuStateRequest(long arg0, int arg1, int arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMenuStateResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetMenuStateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetMenuStateResponse()
        {
        }
        
        public GetMenuStateResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubMenu", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetSubMenuRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public GetSubMenuRequest()
        {
        }
        
        public GetSubMenuRequest(long arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetSubMenuResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetSubMenuResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return;
        
        public GetSubMenuResponse()
        {
        }
        
        public GetSubMenuResponse(long @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pickItem", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class pickItemRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public pickItemRequest()
        {
        }
        
        public pickItemRequest(long arg0, long arg1, int arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="pickItemResponse", WrapperNamespace="http://classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class pickItemResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public pickItemResponse()
        {
        }
        
        public pickItemResponse(bool @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MenuChannel : Sirius.Client.Win32.Core.Menu.Menu, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MenuClient : System.ServiceModel.ClientBase<Sirius.Client.Win32.Core.Menu.Menu>, Sirius.Client.Win32.Core.Menu.Menu
    {
        
        public MenuClient()
        {
        }
        
        public MenuClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MenuClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MenuClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MenuClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.GetMenuItemRectResponse Sirius.Client.Win32.Core.Menu.Menu.GetMenuItemRect(Sirius.Client.Win32.Core.Menu.GetMenuItemRectRequest request)
        {
            return base.Channel.GetMenuItemRect(request);
        }
        
        public bool GetMenuItemRect(long arg0, long arg1, int arg2, Sirius.Client.Win32.Core.Menu.rect arg3)
        {
            Sirius.Client.Win32.Core.Menu.GetMenuItemRectRequest inValue = new Sirius.Client.Win32.Core.Menu.GetMenuItemRectRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            Sirius.Client.Win32.Core.Menu.GetMenuItemRectResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).GetMenuItemRect(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.GetMenuDefaultItemResponse Sirius.Client.Win32.Core.Menu.Menu.GetMenuDefaultItem(Sirius.Client.Win32.Core.Menu.GetMenuDefaultItemRequest request)
        {
            return base.Channel.GetMenuDefaultItem(request);
        }
        
        public int GetMenuDefaultItem(long arg0, int arg1, int arg2)
        {
            Sirius.Client.Win32.Core.Menu.GetMenuDefaultItemRequest inValue = new Sirius.Client.Win32.Core.Menu.GetMenuDefaultItemRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Sirius.Client.Win32.Core.Menu.GetMenuDefaultItemResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).GetMenuDefaultItem(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.GetMenuItemCountResponse Sirius.Client.Win32.Core.Menu.Menu.GetMenuItemCount(Sirius.Client.Win32.Core.Menu.GetMenuItemCountRequest request)
        {
            return base.Channel.GetMenuItemCount(request);
        }
        
        public int GetMenuItemCount(long arg0)
        {
            Sirius.Client.Win32.Core.Menu.GetMenuItemCountRequest inValue = new Sirius.Client.Win32.Core.Menu.GetMenuItemCountRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Menu.GetMenuItemCountResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).GetMenuItemCount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.GetMenuItemIDResponse Sirius.Client.Win32.Core.Menu.Menu.GetMenuItemID(Sirius.Client.Win32.Core.Menu.GetMenuItemIDRequest request)
        {
            return base.Channel.GetMenuItemID(request);
        }
        
        public int GetMenuItemID(long arg0, int arg1)
        {
            Sirius.Client.Win32.Core.Menu.GetMenuItemIDRequest inValue = new Sirius.Client.Win32.Core.Menu.GetMenuItemIDRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Menu.GetMenuItemIDResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).GetMenuItemID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.GetMenuItemInfoResponse Sirius.Client.Win32.Core.Menu.Menu.GetMenuItemInfo(Sirius.Client.Win32.Core.Menu.GetMenuItemInfoRequest request)
        {
            return base.Channel.GetMenuItemInfo(request);
        }
        
        public bool GetMenuItemInfo(long arg0, int arg1, bool arg2, Sirius.Client.Win32.Core.Menu.menuiteminfo arg3)
        {
            Sirius.Client.Win32.Core.Menu.GetMenuItemInfoRequest inValue = new Sirius.Client.Win32.Core.Menu.GetMenuItemInfoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            Sirius.Client.Win32.Core.Menu.GetMenuItemInfoResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).GetMenuItemInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.GetMenuStringResponse Sirius.Client.Win32.Core.Menu.Menu.GetMenuString(Sirius.Client.Win32.Core.Menu.GetMenuStringRequest request)
        {
            return base.Channel.GetMenuString(request);
        }
        
        public int GetMenuString(long arg0, int arg1, System.Nullable<ushort>[] arg2, int arg3, int arg4)
        {
            Sirius.Client.Win32.Core.Menu.GetMenuStringRequest inValue = new Sirius.Client.Win32.Core.Menu.GetMenuStringRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            Sirius.Client.Win32.Core.Menu.GetMenuStringResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).GetMenuString(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.IsMenuResponse Sirius.Client.Win32.Core.Menu.Menu.IsMenu(Sirius.Client.Win32.Core.Menu.IsMenuRequest request)
        {
            return base.Channel.IsMenu(request);
        }
        
        public bool IsMenu(long arg0)
        {
            Sirius.Client.Win32.Core.Menu.IsMenuRequest inValue = new Sirius.Client.Win32.Core.Menu.IsMenuRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Menu.IsMenuResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).IsMenu(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.GetMenuInfoResponse Sirius.Client.Win32.Core.Menu.Menu.GetMenuInfo(Sirius.Client.Win32.Core.Menu.GetMenuInfoRequest request)
        {
            return base.Channel.GetMenuInfo(request);
        }
        
        public bool GetMenuInfo(long arg0, Sirius.Client.Win32.Core.Menu.menuinfo arg1)
        {
            Sirius.Client.Win32.Core.Menu.GetMenuInfoRequest inValue = new Sirius.Client.Win32.Core.Menu.GetMenuInfoRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Menu.GetMenuInfoResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).GetMenuInfo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.GetMenuStateResponse Sirius.Client.Win32.Core.Menu.Menu.GetMenuState(Sirius.Client.Win32.Core.Menu.GetMenuStateRequest request)
        {
            return base.Channel.GetMenuState(request);
        }
        
        public int GetMenuState(long arg0, int arg1, int arg2)
        {
            Sirius.Client.Win32.Core.Menu.GetMenuStateRequest inValue = new Sirius.Client.Win32.Core.Menu.GetMenuStateRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Sirius.Client.Win32.Core.Menu.GetMenuStateResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).GetMenuState(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.GetSubMenuResponse Sirius.Client.Win32.Core.Menu.Menu.GetSubMenu(Sirius.Client.Win32.Core.Menu.GetSubMenuRequest request)
        {
            return base.Channel.GetSubMenu(request);
        }
        
        public long GetSubMenu(long arg0, int arg1)
        {
            Sirius.Client.Win32.Core.Menu.GetSubMenuRequest inValue = new Sirius.Client.Win32.Core.Menu.GetSubMenuRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Menu.GetSubMenuResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).GetSubMenu(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Menu.pickItemResponse Sirius.Client.Win32.Core.Menu.Menu.pickItem(Sirius.Client.Win32.Core.Menu.pickItemRequest request)
        {
            return base.Channel.pickItem(request);
        }
        
        public bool pickItem(long arg0, long arg1, int arg2)
        {
            Sirius.Client.Win32.Core.Menu.pickItemRequest inValue = new Sirius.Client.Win32.Core.Menu.pickItemRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Sirius.Client.Win32.Core.Menu.pickItemResponse retVal = ((Sirius.Client.Win32.Core.Menu.Menu)(this)).pickItem(inValue);
            return retVal.@return;
        }
    }
}
