//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirius.Client.Win32.Core.Button
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", ConfigurationName="Sirius.Client.Win32.Core.Button.Button")]
    public interface Button
    {
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://controls.classes.win32.server.sirius.org/).
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/Button/SetCheckRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/Button/SetCheckResponse")]
        Sirius.Client.Win32.Core.Button.SetCheckResponse SetCheck(Sirius.Client.Win32.Core.Button.SetCheckRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://controls.classes.win32.server.sirius.org/).
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/Button/GetStateRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/Button/GetStateResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Button.GetStateResponse GetState(Sirius.Client.Win32.Core.Button.GetStateRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://controls.classes.win32.server.sirius.org/).
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/Button/GetCheckRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/Button/GetCheckResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Button.GetCheckResponse GetCheck(Sirius.Client.Win32.Core.Button.GetCheckRequest request);
        
        // CODEGEN: Контракт генерации сообщений с пространством имен частей сообщения () не соответствует значению по умолчанию (http://controls.classes.win32.server.sirius.org/).
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/Button/SetStateRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/Button/SetStateResponse")]
        Sirius.Client.Win32.Core.Button.SetStateResponse SetState(Sirius.Client.Win32.Core.Button.SetStateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCheck", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetCheckRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public SetCheckRequest()
        {
        }
        
        public SetCheckRequest(long arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCheckResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetCheckResponse
    {
        
        public SetCheckResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetState", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetStateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        public GetStateRequest()
        {
        }
        
        public GetStateRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStateResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetStateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public GetStateResponse()
        {
        }
        
        public GetStateResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCheck", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetCheckRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        public GetCheckRequest()
        {
        }
        
        public GetCheckRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCheckResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetCheckResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public GetCheckResponse()
        {
        }
        
        public GetCheckResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetState", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetStateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public SetStateRequest()
        {
        }
        
        public SetStateRequest(long arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetStateResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetStateResponse
    {
        
        public SetStateResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ButtonChannel : Sirius.Client.Win32.Core.Button.Button, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ButtonClient : System.ServiceModel.ClientBase<Sirius.Client.Win32.Core.Button.Button>, Sirius.Client.Win32.Core.Button.Button
    {
        
        public ButtonClient()
        {
        }
        
        public ButtonClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ButtonClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ButtonClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ButtonClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Button.SetCheckResponse Sirius.Client.Win32.Core.Button.Button.SetCheck(Sirius.Client.Win32.Core.Button.SetCheckRequest request)
        {
            return base.Channel.SetCheck(request);
        }
        
        public void SetCheck(long arg0, int arg1)
        {
            Sirius.Client.Win32.Core.Button.SetCheckRequest inValue = new Sirius.Client.Win32.Core.Button.SetCheckRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Button.SetCheckResponse retVal = ((Sirius.Client.Win32.Core.Button.Button)(this)).SetCheck(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Button.GetStateResponse Sirius.Client.Win32.Core.Button.Button.GetState(Sirius.Client.Win32.Core.Button.GetStateRequest request)
        {
            return base.Channel.GetState(request);
        }
        
        public int GetState(long arg0)
        {
            Sirius.Client.Win32.Core.Button.GetStateRequest inValue = new Sirius.Client.Win32.Core.Button.GetStateRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Button.GetStateResponse retVal = ((Sirius.Client.Win32.Core.Button.Button)(this)).GetState(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Button.GetCheckResponse Sirius.Client.Win32.Core.Button.Button.GetCheck(Sirius.Client.Win32.Core.Button.GetCheckRequest request)
        {
            return base.Channel.GetCheck(request);
        }
        
        public int GetCheck(long arg0)
        {
            Sirius.Client.Win32.Core.Button.GetCheckRequest inValue = new Sirius.Client.Win32.Core.Button.GetCheckRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Button.GetCheckResponse retVal = ((Sirius.Client.Win32.Core.Button.Button)(this)).GetCheck(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Button.SetStateResponse Sirius.Client.Win32.Core.Button.Button.SetState(Sirius.Client.Win32.Core.Button.SetStateRequest request)
        {
            return base.Channel.SetState(request);
        }
        
        public void SetState(long arg0, int arg1)
        {
            Sirius.Client.Win32.Core.Button.SetStateRequest inValue = new Sirius.Client.Win32.Core.Button.SetStateRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Button.SetStateResponse retVal = ((Sirius.Client.Win32.Core.Button.Button)(this)).SetState(inValue);
        }
    }
}
