//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirius.Client.Win32.Core.Combobox
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", ConfigurationName="Sirius.Client.Win32.Core.Combobox.ComboBox")]
    public interface ComboBox
    {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetItemDataRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetItemDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetItemDataResponse GetItemData(Sirius.Client.Win32.Core.Combobox.GetItemDataRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetCountRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetCountResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetCountResponse GetCount(Sirius.Client.Win32.Core.Combobox.GetCountRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/FindStringRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/FindStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.FindStringResponse FindString(Sirius.Client.Win32.Core.Combobox.FindStringRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetEditSelRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetEditSelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetEditSelResponse GetEditSel(Sirius.Client.Win32.Core.Combobox.GetEditSelRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/FindItemDataRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/FindItemDataResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.FindItemDataResponse FindItemData(Sirius.Client.Win32.Core.Combobox.FindItemDataRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetCurSelRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetCurSelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetCurSelResponse GetCurSel(Sirius.Client.Win32.Core.Combobox.GetCurSelRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetLBTextRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetLBTextResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetLBTextResponse GetLBText(Sirius.Client.Win32.Core.Combobox.GetLBTextRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetLBTextLenRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetLBTextLenResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetLBTextLenResponse GetLBTextLen(Sirius.Client.Win32.Core.Combobox.GetLBTextLenRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetTextRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetTextResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetTextResponse GetText(Sirius.Client.Win32.Core.Combobox.GetTextRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/ResetContentRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/ResetContentResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.ResetContentResponse ResetContent(Sirius.Client.Win32.Core.Combobox.ResetContentRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/SelectStringRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/SelectStringResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.SelectStringResponse SelectString(Sirius.Client.Win32.Core.Combobox.SelectStringRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/SetCurSelRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/SetCurSelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.SetCurSelResponse SetCurSel(Sirius.Client.Win32.Core.Combobox.SetCurSelRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/SetEditSelRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/SetEditSelResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.SetEditSelResponse SetEditSel(Sirius.Client.Win32.Core.Combobox.SetEditSelRequest request);
        
        // CODEGEN: Параметр "arg0" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/SetTextRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/SetTextResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        Sirius.Client.Win32.Core.Combobox.SetTextResponse SetText(Sirius.Client.Win32.Core.Combobox.SetTextRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/ShowDropdownRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/ShowDropdownResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.ShowDropdownResponse ShowDropdown(Sirius.Client.Win32.Core.Combobox.ShowDropdownRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetItemHeightRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetItemHeightResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetItemHeightResponse GetItemHeight(Sirius.Client.Win32.Core.Combobox.GetItemHeightRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/SetItemHeightRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/SetItemHeightResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.SetItemHeightResponse SetItemHeight(Sirius.Client.Win32.Core.Combobox.SetItemHeightRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetDroppedStateRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetDroppedStateResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetDroppedStateResponse GetDroppedState(Sirius.Client.Win32.Core.Combobox.GetDroppedStateRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetTextLengthRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetTextLengthResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetTextLengthResponse GetTextLength(Sirius.Client.Win32.Core.Combobox.GetTextLengthRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/FindStringExactRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/FindStringExactResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.FindStringExactResponse FindStringExact(Sirius.Client.Win32.Core.Combobox.FindStringExactRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://controls.classes.win32.server.sirius.org/ComboBox/GetExtendedUIRequest", ReplyAction="http://controls.classes.win32.server.sirius.org/ComboBox/GetExtendedUIResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(number))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Combobox.GetExtendedUIResponse GetExtendedUI(Sirius.Client.Win32.Core.Combobox.GetExtendedUIRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemData", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetItemDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public GetItemDataRequest()
        {
        }
        
        public GetItemDataRequest(long arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemDataResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetItemDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetItemDataResponse()
        {
        }
        
        public GetItemDataResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCount", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public GetCountRequest()
        {
        }
        
        public GetCountRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCountResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetCountResponse()
        {
        }
        
        public GetCountResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindString", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class FindStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public FindStringRequest()
        {
        }
        
        public FindStringRequest(long arg0, int arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindStringResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class FindStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public FindStringResponse()
        {
        }
        
        public FindStringResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEditSel", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetEditSelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public GetEditSelRequest()
        {
        }
        
        public GetEditSelRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEditSelResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetEditSelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetEditSelResponse()
        {
        }
        
        public GetEditSelResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controls.classes.win32.server.sirius.org/")]
    public partial class lparam : longPTR
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lparam))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controls.classes.win32.server.sirius.org/")]
    public partial class longPTR : integerType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(longPTR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lparam))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controls.classes.win32.server.sirius.org/")]
    public abstract partial class integerType : number
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(integerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(longPTR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(lparam))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://controls.classes.win32.server.sirius.org/")]
    public abstract partial class number
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindItemData", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class FindItemDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sirius.Client.Win32.Core.Combobox.lparam arg2;
        
        public FindItemDataRequest()
        {
        }
        
        public FindItemDataRequest(long arg0, int arg1, Sirius.Client.Win32.Core.Combobox.lparam arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindItemDataResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class FindItemDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public FindItemDataResponse()
        {
        }
        
        public FindItemDataResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurSel", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetCurSelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public GetCurSelRequest()
        {
        }
        
        public GetCurSelRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCurSelResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetCurSelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetCurSelResponse()
        {
        }
        
        public GetCurSelResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLBText", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetLBTextRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public GetLBTextRequest()
        {
        }
        
        public GetLBTextRequest(long arg0, int arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLBTextResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetLBTextResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetLBTextResponse()
        {
        }
        
        public GetLBTextResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLBTextLen", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetLBTextLenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public GetLBTextLenRequest()
        {
        }
        
        public GetLBTextLenRequest(long arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLBTextLenResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetLBTextLenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetLBTextLenResponse()
        {
        }
        
        public GetLBTextLenResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetText", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetTextRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public GetTextRequest()
        {
        }
        
        public GetTextRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTextResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetTextResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public GetTextResponse()
        {
        }
        
        public GetTextResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetContent", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class ResetContentRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public ResetContentRequest()
        {
        }
        
        public ResetContentRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ResetContentResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class ResetContentResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public ResetContentResponse()
        {
        }
        
        public ResetContentResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectString", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SelectStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public SelectStringRequest()
        {
        }
        
        public SelectStringRequest(long arg0, int arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SelectStringResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SelectStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public SelectStringResponse()
        {
        }
        
        public SelectStringResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCurSel", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetCurSelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        public SetCurSelRequest()
        {
        }
        
        public SetCurSelRequest(long arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetCurSelResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetCurSelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public SetCurSelResponse()
        {
        }
        
        public SetCurSelResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetEditSel", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetEditSelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public SetEditSelRequest()
        {
        }
        
        public SetEditSelRequest(long arg0, int arg1, int arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetEditSelResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetEditSelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public SetEditSelResponse()
        {
        }
        
        public SetEditSelResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetText", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetTextRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public SetTextRequest()
        {
        }
        
        public SetTextRequest(long arg0, string arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetTextResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetTextResponse
    {
        
        public SetTextResponse()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShowDropdown", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class ShowDropdownRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool arg1;
        
        public ShowDropdownRequest()
        {
        }
        
        public ShowDropdownRequest(long arg0, bool arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ShowDropdownResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class ShowDropdownResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public ShowDropdownResponse()
        {
        }
        
        public ShowDropdownResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemHeight", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetItemHeightRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public GetItemHeightRequest()
        {
        }
        
        public GetItemHeightRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetItemHeightResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetItemHeightResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetItemHeightResponse()
        {
        }
        
        public GetItemHeightResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetItemHeight", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetItemHeightRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public SetItemHeightRequest()
        {
        }
        
        public SetItemHeightRequest(long arg0, int arg1, int arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetItemHeightResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class SetItemHeightResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public SetItemHeightResponse()
        {
        }
        
        public SetItemHeightResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDroppedState", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetDroppedStateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public GetDroppedStateRequest()
        {
        }
        
        public GetDroppedStateRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDroppedStateResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetDroppedStateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetDroppedStateResponse()
        {
        }
        
        public GetDroppedStateResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTextLength", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetTextLengthRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public GetTextLengthRequest()
        {
        }
        
        public GetTextLengthRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTextLengthResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetTextLengthResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetTextLengthResponse()
        {
        }
        
        public GetTextLengthResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindStringExact", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class FindStringExactRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        public FindStringExactRequest()
        {
        }
        
        public FindStringExactRequest(long arg0, int arg1, string arg2)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FindStringExactResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class FindStringExactResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public FindStringExactResponse()
        {
        }
        
        public FindStringExactResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetExtendedUI", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetExtendedUIRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        public GetExtendedUIRequest()
        {
        }
        
        public GetExtendedUIRequest(long arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetExtendedUIResponse", WrapperNamespace="http://controls.classes.win32.server.sirius.org/", IsWrapped=true)]
    public partial class GetExtendedUIResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://controls.classes.win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public GetExtendedUIResponse()
        {
        }
        
        public GetExtendedUIResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ComboBoxChannel : Sirius.Client.Win32.Core.Combobox.ComboBox, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ComboBoxClient : System.ServiceModel.ClientBase<Sirius.Client.Win32.Core.Combobox.ComboBox>, Sirius.Client.Win32.Core.Combobox.ComboBox
    {
        
        public ComboBoxClient()
        {
        }
        
        public ComboBoxClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ComboBoxClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ComboBoxClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ComboBoxClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetItemDataResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetItemData(Sirius.Client.Win32.Core.Combobox.GetItemDataRequest request)
        {
            return base.Channel.GetItemData(request);
        }
        
        public int GetItemData(long arg0, int arg1)
        {
            Sirius.Client.Win32.Core.Combobox.GetItemDataRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetItemDataRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Combobox.GetItemDataResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetItemData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetCountResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetCount(Sirius.Client.Win32.Core.Combobox.GetCountRequest request)
        {
            return base.Channel.GetCount(request);
        }
        
        public int GetCount(long arg0)
        {
            Sirius.Client.Win32.Core.Combobox.GetCountRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetCountRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Combobox.GetCountResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetCount(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.FindStringResponse Sirius.Client.Win32.Core.Combobox.ComboBox.FindString(Sirius.Client.Win32.Core.Combobox.FindStringRequest request)
        {
            return base.Channel.FindString(request);
        }
        
        public int FindString(long arg0, int arg1, string arg2)
        {
            Sirius.Client.Win32.Core.Combobox.FindStringRequest inValue = new Sirius.Client.Win32.Core.Combobox.FindStringRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Sirius.Client.Win32.Core.Combobox.FindStringResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).FindString(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetEditSelResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetEditSel(Sirius.Client.Win32.Core.Combobox.GetEditSelRequest request)
        {
            return base.Channel.GetEditSel(request);
        }
        
        public int GetEditSel(long arg0)
        {
            Sirius.Client.Win32.Core.Combobox.GetEditSelRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetEditSelRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Combobox.GetEditSelResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetEditSel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.FindItemDataResponse Sirius.Client.Win32.Core.Combobox.ComboBox.FindItemData(Sirius.Client.Win32.Core.Combobox.FindItemDataRequest request)
        {
            return base.Channel.FindItemData(request);
        }
        
        public int FindItemData(long arg0, int arg1, Sirius.Client.Win32.Core.Combobox.lparam arg2)
        {
            Sirius.Client.Win32.Core.Combobox.FindItemDataRequest inValue = new Sirius.Client.Win32.Core.Combobox.FindItemDataRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Sirius.Client.Win32.Core.Combobox.FindItemDataResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).FindItemData(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetCurSelResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetCurSel(Sirius.Client.Win32.Core.Combobox.GetCurSelRequest request)
        {
            return base.Channel.GetCurSel(request);
        }
        
        public int GetCurSel(long arg0)
        {
            Sirius.Client.Win32.Core.Combobox.GetCurSelRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetCurSelRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Combobox.GetCurSelResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetCurSel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetLBTextResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetLBText(Sirius.Client.Win32.Core.Combobox.GetLBTextRequest request)
        {
            return base.Channel.GetLBText(request);
        }
        
        public int GetLBText(long arg0, int arg1, string arg2)
        {
            Sirius.Client.Win32.Core.Combobox.GetLBTextRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetLBTextRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Sirius.Client.Win32.Core.Combobox.GetLBTextResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetLBText(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetLBTextLenResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetLBTextLen(Sirius.Client.Win32.Core.Combobox.GetLBTextLenRequest request)
        {
            return base.Channel.GetLBTextLen(request);
        }
        
        public int GetLBTextLen(long arg0, int arg1)
        {
            Sirius.Client.Win32.Core.Combobox.GetLBTextLenRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetLBTextLenRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Combobox.GetLBTextLenResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetLBTextLen(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetTextResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetText(Sirius.Client.Win32.Core.Combobox.GetTextRequest request)
        {
            return base.Channel.GetText(request);
        }
        
        public string GetText(long arg0)
        {
            Sirius.Client.Win32.Core.Combobox.GetTextRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetTextRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Combobox.GetTextResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetText(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.ResetContentResponse Sirius.Client.Win32.Core.Combobox.ComboBox.ResetContent(Sirius.Client.Win32.Core.Combobox.ResetContentRequest request)
        {
            return base.Channel.ResetContent(request);
        }
        
        public int ResetContent(long arg0)
        {
            Sirius.Client.Win32.Core.Combobox.ResetContentRequest inValue = new Sirius.Client.Win32.Core.Combobox.ResetContentRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Combobox.ResetContentResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).ResetContent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.SelectStringResponse Sirius.Client.Win32.Core.Combobox.ComboBox.SelectString(Sirius.Client.Win32.Core.Combobox.SelectStringRequest request)
        {
            return base.Channel.SelectString(request);
        }
        
        public int SelectString(long arg0, int arg1, string arg2)
        {
            Sirius.Client.Win32.Core.Combobox.SelectStringRequest inValue = new Sirius.Client.Win32.Core.Combobox.SelectStringRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Sirius.Client.Win32.Core.Combobox.SelectStringResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).SelectString(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.SetCurSelResponse Sirius.Client.Win32.Core.Combobox.ComboBox.SetCurSel(Sirius.Client.Win32.Core.Combobox.SetCurSelRequest request)
        {
            return base.Channel.SetCurSel(request);
        }
        
        public int SetCurSel(long arg0, int arg1)
        {
            Sirius.Client.Win32.Core.Combobox.SetCurSelRequest inValue = new Sirius.Client.Win32.Core.Combobox.SetCurSelRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Combobox.SetCurSelResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).SetCurSel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.SetEditSelResponse Sirius.Client.Win32.Core.Combobox.ComboBox.SetEditSel(Sirius.Client.Win32.Core.Combobox.SetEditSelRequest request)
        {
            return base.Channel.SetEditSel(request);
        }
        
        public int SetEditSel(long arg0, int arg1, int arg2)
        {
            Sirius.Client.Win32.Core.Combobox.SetEditSelRequest inValue = new Sirius.Client.Win32.Core.Combobox.SetEditSelRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Sirius.Client.Win32.Core.Combobox.SetEditSelResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).SetEditSel(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.SetTextResponse Sirius.Client.Win32.Core.Combobox.ComboBox.SetText(Sirius.Client.Win32.Core.Combobox.SetTextRequest request)
        {
            return base.Channel.SetText(request);
        }
        
        public void SetText(long arg0, string arg1)
        {
            Sirius.Client.Win32.Core.Combobox.SetTextRequest inValue = new Sirius.Client.Win32.Core.Combobox.SetTextRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Combobox.SetTextResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).SetText(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.ShowDropdownResponse Sirius.Client.Win32.Core.Combobox.ComboBox.ShowDropdown(Sirius.Client.Win32.Core.Combobox.ShowDropdownRequest request)
        {
            return base.Channel.ShowDropdown(request);
        }
        
        public int ShowDropdown(long arg0, bool arg1)
        {
            Sirius.Client.Win32.Core.Combobox.ShowDropdownRequest inValue = new Sirius.Client.Win32.Core.Combobox.ShowDropdownRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Combobox.ShowDropdownResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).ShowDropdown(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetItemHeightResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetItemHeight(Sirius.Client.Win32.Core.Combobox.GetItemHeightRequest request)
        {
            return base.Channel.GetItemHeight(request);
        }
        
        public int GetItemHeight(long arg0)
        {
            Sirius.Client.Win32.Core.Combobox.GetItemHeightRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetItemHeightRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Combobox.GetItemHeightResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetItemHeight(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.SetItemHeightResponse Sirius.Client.Win32.Core.Combobox.ComboBox.SetItemHeight(Sirius.Client.Win32.Core.Combobox.SetItemHeightRequest request)
        {
            return base.Channel.SetItemHeight(request);
        }
        
        public int SetItemHeight(long arg0, int arg1, int arg2)
        {
            Sirius.Client.Win32.Core.Combobox.SetItemHeightRequest inValue = new Sirius.Client.Win32.Core.Combobox.SetItemHeightRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Sirius.Client.Win32.Core.Combobox.SetItemHeightResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).SetItemHeight(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetDroppedStateResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetDroppedState(Sirius.Client.Win32.Core.Combobox.GetDroppedStateRequest request)
        {
            return base.Channel.GetDroppedState(request);
        }
        
        public int GetDroppedState(long arg0)
        {
            Sirius.Client.Win32.Core.Combobox.GetDroppedStateRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetDroppedStateRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Combobox.GetDroppedStateResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetDroppedState(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetTextLengthResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetTextLength(Sirius.Client.Win32.Core.Combobox.GetTextLengthRequest request)
        {
            return base.Channel.GetTextLength(request);
        }
        
        public int GetTextLength(long arg0)
        {
            Sirius.Client.Win32.Core.Combobox.GetTextLengthRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetTextLengthRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Combobox.GetTextLengthResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetTextLength(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.FindStringExactResponse Sirius.Client.Win32.Core.Combobox.ComboBox.FindStringExact(Sirius.Client.Win32.Core.Combobox.FindStringExactRequest request)
        {
            return base.Channel.FindStringExact(request);
        }
        
        public int FindStringExact(long arg0, int arg1, string arg2)
        {
            Sirius.Client.Win32.Core.Combobox.FindStringExactRequest inValue = new Sirius.Client.Win32.Core.Combobox.FindStringExactRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            Sirius.Client.Win32.Core.Combobox.FindStringExactResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).FindStringExact(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Combobox.GetExtendedUIResponse Sirius.Client.Win32.Core.Combobox.ComboBox.GetExtendedUI(Sirius.Client.Win32.Core.Combobox.GetExtendedUIRequest request)
        {
            return base.Channel.GetExtendedUI(request);
        }
        
        public int GetExtendedUI(long arg0)
        {
            Sirius.Client.Win32.Core.Combobox.GetExtendedUIRequest inValue = new Sirius.Client.Win32.Core.Combobox.GetExtendedUIRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Combobox.GetExtendedUIResponse retVal = ((Sirius.Client.Win32.Core.Combobox.ComboBox)(this)).GetExtendedUI(inValue);
            return retVal.@return;
        }
    }
}
