//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://system.server.sirius.org/", ClrNamespace="system.server.sirius.org")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://system.server.sirius.org/", ConfigurationName="DirectoryOperations")]
public interface DirectoryOperations
{
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/DirectoryOperations/moveDirectoryExRequest", ReplyAction="http://system.server.sirius.org/DirectoryOperations/moveDirectoryExResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(system.server.sirius.org.IOException), Action="http://system.server.sirius.org/DirectoryOperations/moveDirectoryEx/Fault/IOExcep" +
        "tion", Name="IOException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    moveDirectoryExResponse moveDirectoryEx(moveDirectoryExRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/DirectoryOperations/moveDirectoryRequest", ReplyAction="http://system.server.sirius.org/DirectoryOperations/moveDirectoryResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(system.server.sirius.org.IOException), Action="http://system.server.sirius.org/DirectoryOperations/moveDirectory/Fault/IOExcepti" +
        "on", Name="IOException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    moveDirectoryResponse moveDirectory(moveDirectoryRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/DirectoryOperations/getContentsExRequest", ReplyAction="http://system.server.sirius.org/DirectoryOperations/getContentsExResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getContentsExResponse getContentsEx(getContentsExRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/DirectoryOperations/createDirectoryExRequest", ReplyAction="http://system.server.sirius.org/DirectoryOperations/createDirectoryExResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    createDirectoryExResponse createDirectoryEx(createDirectoryExRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/DirectoryOperations/copyExRequest", ReplyAction="http://system.server.sirius.org/DirectoryOperations/copyExResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(system.server.sirius.org.IOException), Action="http://system.server.sirius.org/DirectoryOperations/copyEx/Fault/IOException", Name="IOException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    copyExResponse copyEx(copyExRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/DirectoryOperations/copyRequest", ReplyAction="http://system.server.sirius.org/DirectoryOperations/copyResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(system.server.sirius.org.IOException), Action="http://system.server.sirius.org/DirectoryOperations/copy/Fault/IOException", Name="IOException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    copyResponse copy(copyRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/DirectoryOperations/deleteRequest", ReplyAction="http://system.server.sirius.org/DirectoryOperations/deleteResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(system.server.sirius.org.IOException), Action="http://system.server.sirius.org/DirectoryOperations/delete/Fault/IOException", Name="IOException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    deleteResponse delete(deleteRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/DirectoryOperations/existsRequest", ReplyAction="http://system.server.sirius.org/DirectoryOperations/existsResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    existsResponse exists(existsRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/DirectoryOperations/createDirectoryRequest", ReplyAction="http://system.server.sirius.org/DirectoryOperations/createDirectoryResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    createDirectoryResponse createDirectory(createDirectoryRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/DirectoryOperations/getContentsRequest", ReplyAction="http://system.server.sirius.org/DirectoryOperations/getContentsResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getContentsResponse getContents(getContentsRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="moveDirectoryEx", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class moveDirectoryExRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool arg2;
    
    public moveDirectoryExRequest()
    {
    }
    
    public moveDirectoryExRequest(string arg0, string arg1, bool arg2)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
        this.arg2 = arg2;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="moveDirectoryExResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class moveDirectoryExResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return;
    
    public moveDirectoryExResponse()
    {
    }
    
    public moveDirectoryExResponse(bool @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="moveDirectory", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class moveDirectoryRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1;
    
    public moveDirectoryRequest()
    {
    }
    
    public moveDirectoryRequest(string arg0, string arg1)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="moveDirectoryResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class moveDirectoryResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return;
    
    public moveDirectoryResponse()
    {
    }
    
    public moveDirectoryResponse(bool @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getContentsEx", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getContentsExRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool arg1;
    
    public getContentsExRequest()
    {
    }
    
    public getContentsExRequest(string arg0, bool arg1)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getContentsExResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getContentsExResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string[] @return;
    
    public getContentsExResponse()
    {
    }
    
    public getContentsExResponse(string[] @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="createDirectoryEx", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class createDirectoryExRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool arg1;
    
    public createDirectoryExRequest()
    {
    }
    
    public createDirectoryExRequest(string arg0, bool arg1)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="createDirectoryExResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class createDirectoryExResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return;
    
    public createDirectoryExResponse()
    {
    }
    
    public createDirectoryExResponse(bool @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="copyEx", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class copyExRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=2)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool arg2;
    
    public copyExRequest()
    {
    }
    
    public copyExRequest(string arg0, string arg1, bool arg2)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
        this.arg2 = arg2;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="copyExResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class copyExResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return;
    
    public copyExResponse()
    {
    }
    
    public copyExResponse(bool @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="copy", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class copyRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1;
    
    public copyRequest()
    {
    }
    
    public copyRequest(string arg0, string arg1)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="copyResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class copyResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return;
    
    public copyResponse()
    {
    }
    
    public copyResponse(bool @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="delete", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class deleteRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    public deleteRequest()
    {
    }
    
    public deleteRequest(string arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="deleteResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class deleteResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return;
    
    public deleteResponse()
    {
    }
    
    public deleteResponse(bool @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="exists", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class existsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    public existsRequest()
    {
    }
    
    public existsRequest(string arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="existsResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class existsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return;
    
    public existsResponse()
    {
    }
    
    public existsResponse(bool @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="createDirectory", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class createDirectoryRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    public createDirectoryRequest()
    {
    }
    
    public createDirectoryRequest(string arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="createDirectoryResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class createDirectoryResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return;
    
    public createDirectoryResponse()
    {
    }
    
    public createDirectoryResponse(bool @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getContents", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getContentsRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    public getContentsRequest()
    {
    }
    
    public getContentsRequest(string arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getContentsResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getContentsResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public string[] @return;
    
    public getContentsResponse()
    {
    }
    
    public getContentsResponse(string[] @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface DirectoryOperationsChannel : DirectoryOperations, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DirectoryOperationsClient : System.ServiceModel.ClientBase<DirectoryOperations>, DirectoryOperations
{
    
    public DirectoryOperationsClient()
    {
    }
    
    public DirectoryOperationsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DirectoryOperationsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DirectoryOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DirectoryOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    moveDirectoryExResponse DirectoryOperations.moveDirectoryEx(moveDirectoryExRequest request)
    {
        return base.Channel.moveDirectoryEx(request);
    }
    
    public bool moveDirectoryEx(string arg0, string arg1, bool arg2)
    {
        moveDirectoryExRequest inValue = new moveDirectoryExRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        inValue.arg2 = arg2;
        moveDirectoryExResponse retVal = ((DirectoryOperations)(this)).moveDirectoryEx(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    moveDirectoryResponse DirectoryOperations.moveDirectory(moveDirectoryRequest request)
    {
        return base.Channel.moveDirectory(request);
    }
    
    public bool moveDirectory(string arg0, string arg1)
    {
        moveDirectoryRequest inValue = new moveDirectoryRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        moveDirectoryResponse retVal = ((DirectoryOperations)(this)).moveDirectory(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getContentsExResponse DirectoryOperations.getContentsEx(getContentsExRequest request)
    {
        return base.Channel.getContentsEx(request);
    }
    
    public string[] getContentsEx(string arg0, bool arg1)
    {
        getContentsExRequest inValue = new getContentsExRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        getContentsExResponse retVal = ((DirectoryOperations)(this)).getContentsEx(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    createDirectoryExResponse DirectoryOperations.createDirectoryEx(createDirectoryExRequest request)
    {
        return base.Channel.createDirectoryEx(request);
    }
    
    public bool createDirectoryEx(string arg0, bool arg1)
    {
        createDirectoryExRequest inValue = new createDirectoryExRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        createDirectoryExResponse retVal = ((DirectoryOperations)(this)).createDirectoryEx(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    copyExResponse DirectoryOperations.copyEx(copyExRequest request)
    {
        return base.Channel.copyEx(request);
    }
    
    public bool copyEx(string arg0, string arg1, bool arg2)
    {
        copyExRequest inValue = new copyExRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        inValue.arg2 = arg2;
        copyExResponse retVal = ((DirectoryOperations)(this)).copyEx(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    copyResponse DirectoryOperations.copy(copyRequest request)
    {
        return base.Channel.copy(request);
    }
    
    public bool copy(string arg0, string arg1)
    {
        copyRequest inValue = new copyRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        copyResponse retVal = ((DirectoryOperations)(this)).copy(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    deleteResponse DirectoryOperations.delete(deleteRequest request)
    {
        return base.Channel.delete(request);
    }
    
    public bool delete(string arg0)
    {
        deleteRequest inValue = new deleteRequest();
        inValue.arg0 = arg0;
        deleteResponse retVal = ((DirectoryOperations)(this)).delete(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    existsResponse DirectoryOperations.exists(existsRequest request)
    {
        return base.Channel.exists(request);
    }
    
    public bool exists(string arg0)
    {
        existsRequest inValue = new existsRequest();
        inValue.arg0 = arg0;
        existsResponse retVal = ((DirectoryOperations)(this)).exists(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    createDirectoryResponse DirectoryOperations.createDirectory(createDirectoryRequest request)
    {
        return base.Channel.createDirectory(request);
    }
    
    public bool createDirectory(string arg0)
    {
        createDirectoryRequest inValue = new createDirectoryRequest();
        inValue.arg0 = arg0;
        createDirectoryResponse retVal = ((DirectoryOperations)(this)).createDirectory(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getContentsResponse DirectoryOperations.getContents(getContentsRequest request)
    {
        return base.Channel.getContents(request);
    }
    
    public string[] getContents(string arg0)
    {
        getContentsRequest inValue = new getContentsRequest();
        inValue.arg0 = arg0;
        getContentsResponse retVal = ((DirectoryOperations)(this)).getContents(inValue);
        return retVal.@return;
    }
}
namespace system.server.sirius.org
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class IOException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("IOException", "http://system.server.sirius.org/");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}
