//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://system.server.sirius.org/", ClrNamespace="system.server.sirius.org")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://system.server.sirius.org/", ConfigurationName="SystemOperations")]
public interface SystemOperations
{
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/SystemOperations/getEnvironmentVariableRequest", ReplyAction="http://system.server.sirius.org/SystemOperations/getEnvironmentVariableResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getEnvironmentVariableResponse getEnvironmentVariable(getEnvironmentVariableRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/SystemOperations/setEnvironmentVariableRequest", ReplyAction="http://system.server.sirius.org/SystemOperations/setEnvironmentVariableResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(system.server.sirius.org.IOException), Action="http://system.server.sirius.org/SystemOperations/setEnvironmentVariable/Fault/IOE" +
        "xception", Name="IOException")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    setEnvironmentVariableResponse setEnvironmentVariable(setEnvironmentVariableRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/SystemOperations/getMachineNameRequest", ReplyAction="http://system.server.sirius.org/SystemOperations/getMachineNameResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getMachineNameResponse getMachineName(getMachineNameRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/SystemOperations/getFreeMemoryRequest", ReplyAction="http://system.server.sirius.org/SystemOperations/getFreeMemoryResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getFreeMemoryResponse getFreeMemory(getFreeMemoryRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/SystemOperations/getFreeDiskSpaceRequest", ReplyAction="http://system.server.sirius.org/SystemOperations/getFreeDiskSpaceResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getFreeDiskSpaceResponse getFreeDiskSpace(getFreeDiskSpaceRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/SystemOperations/getSystemMetricsRequest", ReplyAction="http://system.server.sirius.org/SystemOperations/getSystemMetricsResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeMemoryResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeMemory))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCurrentUserResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCurrentUser))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeDiskSpaceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeDiskSpace))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getEnvironmentVariableResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getEnvironmentVariable))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setDateResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setDate))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDateResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDate))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getMachineNameResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getMachineName))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSystemMetricsResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSystemMetrics))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IOException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setEnvironmentVariableResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setEnvironmentVariable))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getSystemMetricsResponse1 getSystemMetrics(getSystemMetricsRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/SystemOperations/getCurrentUserRequest", ReplyAction="http://system.server.sirius.org/SystemOperations/getCurrentUserResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeMemoryResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeMemory))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCurrentUserResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCurrentUser))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeDiskSpaceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeDiskSpace))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getEnvironmentVariableResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getEnvironmentVariable))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setDateResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setDate))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDateResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDate))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getMachineNameResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getMachineName))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSystemMetricsResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSystemMetrics))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IOException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setEnvironmentVariableResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setEnvironmentVariable))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getCurrentUserResponse1 getCurrentUser(getCurrentUserRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/SystemOperations/getDateRequest", ReplyAction="http://system.server.sirius.org/SystemOperations/getDateResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeMemoryResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeMemory))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCurrentUserResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCurrentUser))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeDiskSpaceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeDiskSpace))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getEnvironmentVariableResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getEnvironmentVariable))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setDateResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setDate))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDateResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDate))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getMachineNameResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getMachineName))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSystemMetricsResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSystemMetrics))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IOException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setEnvironmentVariableResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setEnvironmentVariable))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    getDateResponse1 getDate(getDateRequest request);
    
    // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
    [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/SystemOperations/setDateRequest", ReplyAction="http://system.server.sirius.org/SystemOperations/setDateResponse")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeMemoryResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeMemory))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCurrentUserResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getCurrentUser))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeDiskSpaceResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getFreeDiskSpace))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getEnvironmentVariableResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getEnvironmentVariable))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setDateResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setDate))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDateResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getDate))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getMachineNameResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getMachineName))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSystemMetricsResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getSystemMetrics))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(IOException))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setEnvironmentVariableResponse))]
    [System.ServiceModel.ServiceKnownTypeAttribute(typeof(setEnvironmentVariable))]
    [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
    setDateResponse1 setDate(setDateRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getEnvironmentVariable", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getEnvironmentVariableRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    public getEnvironmentVariableRequest()
    {
    }
    
    public getEnvironmentVariableRequest(string arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getEnvironmentVariableResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getEnvironmentVariableResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return;
    
    public getEnvironmentVariableResponse()
    {
    }
    
    public getEnvironmentVariableResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="setEnvironmentVariable", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class setEnvironmentVariableRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg1;
    
    public setEnvironmentVariableRequest()
    {
    }
    
    public setEnvironmentVariableRequest(string arg0, string arg1)
    {
        this.arg0 = arg0;
        this.arg1 = arg1;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="setEnvironmentVariableResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class setEnvironmentVariableResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return;
    
    public setEnvironmentVariableResponse()
    {
    }
    
    public setEnvironmentVariableResponse(bool @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getMachineName", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getMachineNameRequest
{
    
    public getMachineNameRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getMachineNameResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getMachineNameResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return;
    
    public getMachineNameResponse()
    {
    }
    
    public getMachineNameResponse(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getFreeMemory", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getFreeMemoryRequest
{
    
    public getFreeMemoryRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getFreeMemoryResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getFreeMemoryResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long @return;
    
    public getFreeMemoryResponse()
    {
    }
    
    public getFreeMemoryResponse(long @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getFreeDiskSpace", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getFreeDiskSpaceRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string arg0;
    
    public getFreeDiskSpaceRequest()
    {
    }
    
    public getFreeDiskSpaceRequest(string arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getFreeDiskSpaceResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getFreeDiskSpaceResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public long @return;
    
    public getFreeDiskSpaceResponse()
    {
    }
    
    public getFreeDiskSpaceResponse(long @return)
    {
        this.@return = @return;
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getFreeMemoryResponse
{
    
    private long returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public long @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getFreeMemory
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getCurrentUserResponse
{
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getCurrentUser
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getFreeDiskSpaceResponse
{
    
    private long returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public long @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getFreeDiskSpace
{
    
    private string arg0Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string arg0
    {
        get
        {
            return this.arg0Field;
        }
        set
        {
            this.arg0Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getEnvironmentVariableResponse
{
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getEnvironmentVariable
{
    
    private string arg0Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string arg0
    {
        get
        {
            return this.arg0Field;
        }
        set
        {
            this.arg0Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class setDateResponse
{
    
    private bool returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public bool @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class setDate
{
    
    private System.DateTime arg0Field;
    
    private bool arg0FieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public System.DateTime arg0
    {
        get
        {
            return this.arg0Field;
        }
        set
        {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool arg0Specified
    {
        get
        {
            return this.arg0FieldSpecified;
        }
        set
        {
            this.arg0FieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getDateResponse
{
    
    private System.DateTime returnField;
    
    private bool returnFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public System.DateTime @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool returnSpecified
    {
        get
        {
            return this.returnFieldSpecified;
        }
        set
        {
            this.returnFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getDate
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getMachineNameResponse
{
    
    private string returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getMachineName
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getSystemMetricsResponse
{
    
    private object returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public object @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class getSystemMetrics
{
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class IOException
{
    
    private string messageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class setEnvironmentVariableResponse
{
    
    private bool returnField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public bool @return
    {
        get
        {
            return this.returnField;
        }
        set
        {
            this.returnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://system.server.sirius.org/")]
public partial class setEnvironmentVariable
{
    
    private string arg0Field;
    
    private string arg1Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
    public string arg0
    {
        get
        {
            return this.arg0Field;
        }
        set
        {
            this.arg0Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
    public string arg1
    {
        get
        {
            return this.arg1Field;
        }
        set
        {
            this.arg1Field = value;
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getSystemMetrics", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getSystemMetricsRequest
{
    
    public getSystemMetricsRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getSystemMetricsResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getSystemMetricsResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object @return;
    
    public getSystemMetricsResponse1()
    {
    }
    
    public getSystemMetricsResponse1(object @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentUser", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getCurrentUserRequest
{
    
    public getCurrentUserRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getCurrentUserResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getCurrentUserResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string @return;
    
    public getCurrentUserResponse1()
    {
    }
    
    public getCurrentUserResponse1(string @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDate", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getDateRequest
{
    
    public getDateRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="getDateResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class getDateResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime @return;
    
    public getDateResponse1()
    {
    }
    
    public getDateResponse1(System.DateTime @return)
    {
        this.@return = @return;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="setDate", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class setDateRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public System.DateTime arg0;
    
    public setDateRequest()
    {
    }
    
    public setDateRequest(System.DateTime arg0)
    {
        this.arg0 = arg0;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="setDateResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
public partial class setDateResponse1
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public bool @return;
    
    public setDateResponse1()
    {
    }
    
    public setDateResponse1(bool @return)
    {
        this.@return = @return;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface SystemOperationsChannel : SystemOperations, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class SystemOperationsClient : System.ServiceModel.ClientBase<SystemOperations>, SystemOperations
{
    
    public SystemOperationsClient()
    {
    }
    
    public SystemOperationsClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SystemOperationsClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SystemOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SystemOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getEnvironmentVariableResponse SystemOperations.getEnvironmentVariable(getEnvironmentVariableRequest request)
    {
        return base.Channel.getEnvironmentVariable(request);
    }
    
    public string getEnvironmentVariable(string arg0)
    {
        getEnvironmentVariableRequest inValue = new getEnvironmentVariableRequest();
        inValue.arg0 = arg0;
        getEnvironmentVariableResponse retVal = ((SystemOperations)(this)).getEnvironmentVariable(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    setEnvironmentVariableResponse SystemOperations.setEnvironmentVariable(setEnvironmentVariableRequest request)
    {
        return base.Channel.setEnvironmentVariable(request);
    }
    
    public bool setEnvironmentVariable(string arg0, string arg1)
    {
        setEnvironmentVariableRequest inValue = new setEnvironmentVariableRequest();
        inValue.arg0 = arg0;
        inValue.arg1 = arg1;
        setEnvironmentVariableResponse retVal = ((SystemOperations)(this)).setEnvironmentVariable(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getMachineNameResponse SystemOperations.getMachineName(getMachineNameRequest request)
    {
        return base.Channel.getMachineName(request);
    }
    
    public string getMachineName()
    {
        getMachineNameRequest inValue = new getMachineNameRequest();
        getMachineNameResponse retVal = ((SystemOperations)(this)).getMachineName(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getFreeMemoryResponse SystemOperations.getFreeMemory(getFreeMemoryRequest request)
    {
        return base.Channel.getFreeMemory(request);
    }
    
    public long getFreeMemory()
    {
        getFreeMemoryRequest inValue = new getFreeMemoryRequest();
        getFreeMemoryResponse retVal = ((SystemOperations)(this)).getFreeMemory(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getFreeDiskSpaceResponse SystemOperations.getFreeDiskSpace(getFreeDiskSpaceRequest request)
    {
        return base.Channel.getFreeDiskSpace(request);
    }
    
    public long getFreeDiskSpace(string arg0)
    {
        getFreeDiskSpaceRequest inValue = new getFreeDiskSpaceRequest();
        inValue.arg0 = arg0;
        getFreeDiskSpaceResponse retVal = ((SystemOperations)(this)).getFreeDiskSpace(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getSystemMetricsResponse1 SystemOperations.getSystemMetrics(getSystemMetricsRequest request)
    {
        return base.Channel.getSystemMetrics(request);
    }
    
    public object getSystemMetrics()
    {
        getSystemMetricsRequest inValue = new getSystemMetricsRequest();
        getSystemMetricsResponse1 retVal = ((SystemOperations)(this)).getSystemMetrics(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getCurrentUserResponse1 SystemOperations.getCurrentUser(getCurrentUserRequest request)
    {
        return base.Channel.getCurrentUser(request);
    }
    
    public string getCurrentUser()
    {
        getCurrentUserRequest inValue = new getCurrentUserRequest();
        getCurrentUserResponse1 retVal = ((SystemOperations)(this)).getCurrentUser(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    getDateResponse1 SystemOperations.getDate(getDateRequest request)
    {
        return base.Channel.getDate(request);
    }
    
    public System.DateTime getDate()
    {
        getDateRequest inValue = new getDateRequest();
        getDateResponse1 retVal = ((SystemOperations)(this)).getDate(inValue);
        return retVal.@return;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    setDateResponse1 SystemOperations.setDate(setDateRequest request)
    {
        return base.Channel.setDate(request);
    }
    
    public bool setDate(System.DateTime arg0)
    {
        setDateRequest inValue = new setDateRequest();
        inValue.arg0 = arg0;
        setDateResponse1 retVal = ((SystemOperations)(this)).setDate(inValue);
        return retVal.@return;
    }
}
namespace system.server.sirius.org
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class IOException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("IOException", "http://system.server.sirius.org/");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
}
