call gem install rubygems-update -v 2.0.3
call gem install rubygems-tasks -v 0.2.3
call gem install rdoc -v 4.0.1
call gem install rake -v 10.0.3
call gem install httpclient -v 2.3.0.1
call gem install handsoap -v 1.1.8
call gem install json -v 1.5.4
call gem install cucumber -v 1.2.1
call gem install github_api -v 0.10.2
call gem install rubocop -v 0.3.2
call gem install term-ansicolor -v 1.1.4
