require 'rubygems'
require 'rubygems/package_task'
require 'cucumber'
require 'cucumber/rake/task'
require 'rake/testtask'
require 'fileutils'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "Sirius Ruby client"
  s.name = "sirius-client-core"
  s.version = File.read('VERSION').chomp
  s.requirements = "none"
  s.files = FileList["lib/**/*.rb", "Rakefile"]
  s.homepage = "http://github.com/mkolisnyk/Sirius"
  s.description = "The client for Sirius system"
  s.authors="Myk Kolisnyk"
  s.email="kolesnik.nickolay@gmail.com"
end

task :clean do |t|
  FileUtils.rm_r 'pkg', :force => true
end

task :rubocop do |t|
  includes = Dir['lib/**/*']
  excludes = Dir['lib/sirius/core/system/**/*']
  
  file_list = (includes - excludes ).reject {|fn| File.directory?(fn)}   
  
  file_list.each do |path|
    sh "call rubocop -c .rubocop.yml -e #{path}"
  end
end

task :issue_get do |t|
  github = Github.new do |config|
    config.repo        = 'Sirius'
    config.user        = 'mkolisnyk'
    config.oauth_token = '6cbcb8e3d8031bdd0637256be9da89c57ea26949'
    config.adapter     = :net_http
    config.ssl         = {:verify => false}
  end
  
  FileList['./tests/features/**/*.feature'].each do |x|
    File.delete(x)
  end
    
  github.issues.list( :labels=>"System") do |issue|
    feature_name = "#{issue.title.gsub(/[ :]/,'')}.feature"
    puts "Writing #{feature_name}"
    unless File.exists?("./tests/features/#{feature_name}")
      file = File.open("./tests/features/#{feature_name}","a")
      file.puts("# Requirement: #{issue.milestone.title}")
      file.write("# #{issue.milestone.description.gsub("\n","\n# ").gsub("\r",'')}")
      file.close  
    end
    
    file = File.open("./tests/features/#{feature_name}","a")
    file.puts("")
    issue.labels.each do |label|
      file.write("@#{label.name} ")
    end
    file.puts("")
    file.puts("Feature: #{issue.title}")
    file.puts("")
    file.puts("#{issue.body.gsub("\r",'').gsub('**Scenario:**','Scenario:')}")
    file.close
  end
  puts 'done'
end

Rake::TestTask.new(:install_test) do |task|
  task.name = 'install_test'
  task.libs << "test"
  task.test_files = FileList['tests/install/**/*.rb']
  task.verbose = true
end

Gem::PackageTask.new(spec) do |pkg|
end

Cucumber::Rake::Task.new(:test) do |t|
  t.cucumber_opts = "tests/features --format pretty --guess"
end

task :push => [:package] do |t| 
  sh "call gem push -V pkg/#{spec.name}-#{spec.version}.gem"
end

task :all => [:clean,:rubocop,:package,:install_test,:issue_get,:test]