//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sirius.Client.Win32.Core.Utils
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://win32.server.sirius.org/", ConfigurationName="Sirius.Client.Win32.Core.Utils.Win32Utils")]
    public interface Win32Utils
    {
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://win32.server.sirius.org/Win32Utils/searchWindowRequest", ReplyAction="http://win32.server.sirius.org/Win32Utils/searchWindowResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Utils.searchWindowResponse searchWindow(Sirius.Client.Win32.Core.Utils.searchWindowRequest request);
        
        // CODEGEN: Параметр "return" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://win32.server.sirius.org/Win32Utils/searchSameThreadWindowRequest", ReplyAction="http://win32.server.sirius.org/Win32Utils/searchSameThreadWindowResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        Sirius.Client.Win32.Core.Utils.searchSameThreadWindowResponse searchSameThreadWindow(Sirius.Client.Win32.Core.Utils.searchSameThreadWindowRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://win32.server.sirius.org/")]
    public partial class win32Locator
    {
        
        private string captionField;
        
        private long hwndField;
        
        private int indexField;
        
        private long parentField;
        
        private string winClassField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string caption
        {
            get
            {
                return this.captionField;
            }
            set
            {
                this.captionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long hwnd
        {
            get
            {
                return this.hwndField;
            }
            set
            {
                this.hwndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int index
        {
            get
            {
                return this.indexField;
            }
            set
            {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string winClass
        {
            get
            {
                return this.winClassField;
            }
            set
            {
                this.winClassField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchWindow", WrapperNamespace="http://win32.server.sirius.org/", IsWrapped=true)]
    public partial class searchWindowRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sirius.Client.Win32.Core.Utils.win32Locator arg0;
        
        public searchWindowRequest()
        {
        }
        
        public searchWindowRequest(Sirius.Client.Win32.Core.Utils.win32Locator arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchWindowResponse", WrapperNamespace="http://win32.server.sirius.org/", IsWrapped=true)]
    public partial class searchWindowResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return;
        
        public searchWindowResponse()
        {
        }
        
        public searchWindowResponse(long @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchSameThreadWindow", WrapperNamespace="http://win32.server.sirius.org/", IsWrapped=true)]
    public partial class searchSameThreadWindowRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://win32.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Sirius.Client.Win32.Core.Utils.win32Locator arg1;
        
        public searchSameThreadWindowRequest()
        {
        }
        
        public searchSameThreadWindowRequest(long arg0, Sirius.Client.Win32.Core.Utils.win32Locator arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="searchSameThreadWindowResponse", WrapperNamespace="http://win32.server.sirius.org/", IsWrapped=true)]
    public partial class searchSameThreadWindowResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://win32.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long @return;
        
        public searchSameThreadWindowResponse()
        {
        }
        
        public searchSameThreadWindowResponse(long @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Win32UtilsChannel : Sirius.Client.Win32.Core.Utils.Win32Utils, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Win32UtilsClient : System.ServiceModel.ClientBase<Sirius.Client.Win32.Core.Utils.Win32Utils>, Sirius.Client.Win32.Core.Utils.Win32Utils
    {
        
        public Win32UtilsClient()
        {
        }
        
        public Win32UtilsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public Win32UtilsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Win32UtilsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public Win32UtilsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Utils.searchWindowResponse Sirius.Client.Win32.Core.Utils.Win32Utils.searchWindow(Sirius.Client.Win32.Core.Utils.searchWindowRequest request)
        {
            return base.Channel.searchWindow(request);
        }
        
        public long searchWindow(Sirius.Client.Win32.Core.Utils.win32Locator arg0)
        {
            Sirius.Client.Win32.Core.Utils.searchWindowRequest inValue = new Sirius.Client.Win32.Core.Utils.searchWindowRequest();
            inValue.arg0 = arg0;
            Sirius.Client.Win32.Core.Utils.searchWindowResponse retVal = ((Sirius.Client.Win32.Core.Utils.Win32Utils)(this)).searchWindow(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Win32.Core.Utils.searchSameThreadWindowResponse Sirius.Client.Win32.Core.Utils.Win32Utils.searchSameThreadWindow(Sirius.Client.Win32.Core.Utils.searchSameThreadWindowRequest request)
        {
            return base.Channel.searchSameThreadWindow(request);
        }
        
        public long searchSameThreadWindow(long arg0, Sirius.Client.Win32.Core.Utils.win32Locator arg1)
        {
            Sirius.Client.Win32.Core.Utils.searchSameThreadWindowRequest inValue = new Sirius.Client.Win32.Core.Utils.searchSameThreadWindowRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            Sirius.Client.Win32.Core.Utils.searchSameThreadWindowResponse retVal = ((Sirius.Client.Win32.Core.Utils.Win32Utils)(this)).searchSameThreadWindow(inValue);
            return retVal.@return;
        }
    }
}
