require 'rubygems/package_task'

  spec = Gem::Specification.new do |s|
    s.platform = Gem::Platform::RUBY
    s.summary = "Sirius Ruby client"
    s.name = "sirius-client"
    s.version = ENV['BUILD_VERSION']
    s.requirements = "none"
    s.files = FileList["core/**/*.rb", "Rakefile"]
    s.homepage = "http://github.com/mkolisnyk/Sirius"
    s.description = "The client for Sirius system"
    s.authors="Myk Kolisnyk"
    s.email="kolesnik.nickolay@gmail.com"
  end

  Gem::PackageTask.new(spec) do |pkg|
  end