require 'rubygems'
require 'rubygems/package_task'
require 'cucumber'
require 'cucumber/rake/task.rb'
require 'rubygems/tasks'
require 'rubocop'

spec = Gem::Specification.new do |s|
  s.platform = Gem::Platform::RUBY
  s.summary = "Sirius Ruby client"
  s.name = "sirius-client"
  s.version = File.read('VERSION').chomp
  s.requirements = "none"
  s.files = FileList["lib/**/*.rb", "Rakefile","README.rdoc"]
  s.homepage = "http://github.com/mkolisnyk/Sirius"
  
  s.description = '''
  The core ruby client part for Sirius system. 
  '''
  
  s.authors="Myk Kolisnyk"
  s.email="kolesnik.nickolay@gmail.com"
  s.add_dependency('sirius-client-core', '>= 0.0')
  s.add_dependency('sirius-client-win32', '>= 0.0')
  s.add_dependency('sirius-client-web', '>= 0.0')
end

Cucumber::Rake::Task.new(:test) do |t|
  t.cucumber_opts = "tests/features --format pretty --guess"
end

task :rubocop do |t|
  sh 'call rubocop -c .rubocop.yml -e lib'
end

task :saikuro do |t|
  sh 'call saikuro -c -t -i lib -y 0 -w 11 -e 16 -o out/'
end

Gem::PackageTask.new(spec) do |pkg| 
end

task :push => [:package] do |t| 
  sh "call gem push  -k sirius_api_key -V pkg/#{spec.name}-#{spec.version}.gem"
end