//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://system.server.sirius.org/", ClrNamespace="Sirius.Client.Core.Sys.File")]


namespace Sirius.Client.Core.Sys.File
{
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class IOException : object, System.Xml.Serialization.IXmlSerializable
    {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("IOException", "http://system.server.sirius.org/");
        
        public System.Xml.XmlNode[] Nodes
        {
            get
            {
                return this.nodesField;
            }
            set
            {
                this.nodesField = value;
            }
        }
        
        public void ReadXml(System.Xml.XmlReader reader)
        {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer)
        {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema()
        {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas)
        {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://system.server.sirius.org/", ConfigurationName="Sirius.Client.Core.Sys.File.FileOperations")]
    public interface FileOperations
    {
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/fileExistsRequest", ReplyAction="http://system.server.sirius.org/FileOperations/fileExistsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.fileExistsResponse fileExists(Sirius.Client.Core.Sys.File.fileExistsRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/copyExRequest", ReplyAction="http://system.server.sirius.org/FileOperations/copyExResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/copyEx/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.copyExResponse copyEx(Sirius.Client.Core.Sys.File.copyExRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/createFileRequest", ReplyAction="http://system.server.sirius.org/FileOperations/createFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.createFileResponse createFile(Sirius.Client.Core.Sys.File.createFileRequest request);
        
        // CODEGEN: Параметр "content" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/getFileContentsRequest", ReplyAction="http://system.server.sirius.org/FileOperations/getFileContentsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/getFileContents/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="content")]
        Sirius.Client.Core.Sys.File.getFileContentsResponse getFileContents(Sirius.Client.Core.Sys.File.getFileContentsRequest request);
        
        // CODEGEN: Параметр "content" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/getFileContentsEx2Request", ReplyAction="http://system.server.sirius.org/FileOperations/getFileContentsEx2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/getFileContentsEx2/Fault/IOExcepti" +
            "on", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="content")]
        Sirius.Client.Core.Sys.File.getFileContentsEx2Response getFileContentsEx2(Sirius.Client.Core.Sys.File.getFileContentsEx2Request request);
        
        // CODEGEN: Параметр "content" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/getFileContentsExRequest", ReplyAction="http://system.server.sirius.org/FileOperations/getFileContentsExResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/getFileContentsEx/Fault/IOExceptio" +
            "n", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="content")]
        Sirius.Client.Core.Sys.File.getFileContentsExResponse getFileContentsEx(Sirius.Client.Core.Sys.File.getFileContentsExRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/appendExRequest", ReplyAction="http://system.server.sirius.org/FileOperations/appendExResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/appendEx/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.appendExResponse appendEx(Sirius.Client.Core.Sys.File.appendExRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/createFileExRequest", ReplyAction="http://system.server.sirius.org/FileOperations/createFileExResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.createFileExResponse createFileEx(Sirius.Client.Core.Sys.File.createFileExRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/deleteFileRequest", ReplyAction="http://system.server.sirius.org/FileOperations/deleteFileResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.deleteFileResponse deleteFile(Sirius.Client.Core.Sys.File.deleteFileRequest request);
        
        // CODEGEN: Параметр "content" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/getAllBytesRequest", ReplyAction="http://system.server.sirius.org/FileOperations/getAllBytesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="content")]
        Sirius.Client.Core.Sys.File.getAllBytesResponse getAllBytes(Sirius.Client.Core.Sys.File.getAllBytesRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/moveExRequest", ReplyAction="http://system.server.sirius.org/FileOperations/moveExResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/moveEx/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.moveExResponse moveEx(Sirius.Client.Core.Sys.File.moveExRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/writeExRequest", ReplyAction="http://system.server.sirius.org/FileOperations/writeExResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/writeEx/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.writeExResponse writeEx(Sirius.Client.Core.Sys.File.writeExRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/appendRequest", ReplyAction="http://system.server.sirius.org/FileOperations/appendResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/append/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.appendResponse append(Sirius.Client.Core.Sys.File.appendRequest request);
        
        // CODEGEN: Параметр "fileSize" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/sizeRequest", ReplyAction="http://system.server.sirius.org/FileOperations/sizeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fileSize")]
        Sirius.Client.Core.Sys.File.sizeResponse size(Sirius.Client.Core.Sys.File.sizeRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/writeRequest", ReplyAction="http://system.server.sirius.org/FileOperations/writeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/write/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.writeResponse write(Sirius.Client.Core.Sys.File.writeRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/copyRequest", ReplyAction="http://system.server.sirius.org/FileOperations/copyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/copy/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.copyResponse copy(Sirius.Client.Core.Sys.File.copyRequest request);
        
        // CODEGEN: Параметр "content" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/headRequest", ReplyAction="http://system.server.sirius.org/FileOperations/headResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/head/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="content")]
        Sirius.Client.Core.Sys.File.headResponse head(Sirius.Client.Core.Sys.File.headRequest request);
        
        // CODEGEN: Параметр "content" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/tailRequest", ReplyAction="http://system.server.sirius.org/FileOperations/tailResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/tail/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="content")]
        Sirius.Client.Core.Sys.File.tailResponse tail(Sirius.Client.Core.Sys.File.tailRequest request);
        
        // CODEGEN: Параметр "status" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://system.server.sirius.org/FileOperations/moveRequest", ReplyAction="http://system.server.sirius.org/FileOperations/moveResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Sirius.Client.Core.Sys.File.IOException), Action="http://system.server.sirius.org/FileOperations/move/Fault/IOException", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [return: System.ServiceModel.MessageParameterAttribute(Name="status")]
        Sirius.Client.Core.Sys.File.moveResponse move(Sirius.Client.Core.Sys.File.moveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileExists", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class fileExistsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        public fileExistsRequest()
        {
        }
        
        public fileExistsRequest(string fileName)
        {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="fileExistsResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class fileExistsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public fileExistsResponse()
        {
        }
        
        public fileExistsResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="copyEx", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class copyExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string origin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destination;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool overwrite;
        
        public copyExRequest()
        {
        }
        
        public copyExRequest(string origin, string destination, bool overwrite)
        {
            this.origin = origin;
            this.destination = destination;
            this.overwrite = overwrite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="copyExResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class copyExResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public copyExResponse()
        {
        }
        
        public copyExResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFile", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class createFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        public createFileRequest()
        {
        }
        
        public createFileRequest(string fileName)
        {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFileResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class createFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public createFileResponse()
        {
        }
        
        public createFileResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFileContents", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class getFileContentsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string path;
        
        public getFileContentsRequest()
        {
        }
        
        public getFileContentsRequest(string path)
        {
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFileContentsResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class getFileContentsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] content;
        
        public getFileContentsResponse()
        {
        }
        
        public getFileContentsResponse(string[] content)
        {
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFileContentsEx2", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class getFileContentsEx2Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int number;
        
        public getFileContentsEx2Request()
        {
        }
        
        public getFileContentsEx2Request(string path, int start, int number)
        {
            this.path = path;
            this.start = start;
            this.number = number;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFileContentsEx2Response", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class getFileContentsEx2Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] content;
        
        public getFileContentsEx2Response()
        {
        }
        
        public getFileContentsEx2Response(string[] content)
        {
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFileContentsEx", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class getFileContentsExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int start;
        
        public getFileContentsExRequest()
        {
        }
        
        public getFileContentsExRequest(string path, int start)
        {
            this.path = path;
            this.start = start;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getFileContentsExResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class getFileContentsExResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] content;
        
        public getFileContentsExResponse()
        {
        }
        
        public getFileContentsExResponse(string[] content)
        {
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="appendEx", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class appendExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        public appendExRequest()
        {
        }
        
        public appendExRequest(string path, string text)
        {
            this.path = path;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="appendExResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class appendExResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public appendExResponse()
        {
        }
        
        public appendExResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFileEx", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class createFileExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool overwrite;
        
        public createFileExRequest()
        {
        }
        
        public createFileExRequest(string fileName, bool overwrite)
        {
            this.fileName = fileName;
            this.overwrite = overwrite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createFileExResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class createFileExResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public createFileExResponse()
        {
        }
        
        public createFileExResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFile", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class deleteFileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        public deleteFileRequest()
        {
        }
        
        public deleteFileRequest(string fileName)
        {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteFileResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class deleteFileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public deleteFileResponse()
        {
        }
        
        public deleteFileResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllBytes", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class getAllBytesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        public getAllBytesRequest()
        {
        }
        
        public getAllBytesRequest(string fileName)
        {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAllBytesResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class getAllBytesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] content;
        
        public getAllBytesResponse()
        {
        }
        
        public getAllBytesResponse(byte[] content)
        {
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveEx", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class moveExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string origin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destination;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool overwrite;
        
        public moveExRequest()
        {
        }
        
        public moveExRequest(string origin, string destination, bool overwrite)
        {
            this.origin = origin;
            this.destination = destination;
            this.overwrite = overwrite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveExResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class moveExResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public moveExResponse()
        {
        }
        
        public moveExResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="writeEx", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class writeExRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string text;
        
        public writeExRequest()
        {
        }
        
        public writeExRequest(string path, string text)
        {
            this.path = path;
            this.text = text;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="writeExResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class writeExResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public writeExResponse()
        {
        }
        
        public writeExResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="append", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class appendRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] content;
        
        public appendRequest()
        {
        }
        
        public appendRequest(string path, byte[] content)
        {
            this.path = path;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="appendResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class appendResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public appendResponse()
        {
        }
        
        public appendResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="size", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class sizeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fileName;
        
        public sizeRequest()
        {
        }
        
        public sizeRequest(string fileName)
        {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="sizeResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class sizeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long fileSize;
        
        public sizeResponse()
        {
        }
        
        public sizeResponse(long fileSize)
        {
            this.fileSize = fileSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="write", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class writeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", IsNullable=true)]
        public byte[] content;
        
        public writeRequest()
        {
        }
        
        public writeRequest(string path, byte[] content)
        {
            this.path = path;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="writeResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class writeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public writeResponse()
        {
        }
        
        public writeResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="copy", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class copyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string origin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destination;
        
        public copyRequest()
        {
        }
        
        public copyRequest(string origin, string destination)
        {
            this.origin = origin;
            this.destination = destination;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="copyResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class copyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public copyResponse()
        {
        }
        
        public copyResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="head", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class headRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int lines;
        
        public headRequest()
        {
        }
        
        public headRequest(string path, int lines)
        {
            this.path = path;
            this.lines = lines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="headResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class headResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] content;
        
        public headResponse()
        {
        }
        
        public headResponse(string[] content)
        {
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tail", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class tailRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string path;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int lines;
        
        public tailRequest()
        {
        }
        
        public tailRequest(string path, int lines)
        {
            this.path = path;
            this.lines = lines;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="tailResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class tailResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] content;
        
        public tailResponse()
        {
        }
        
        public tailResponse(string[] content)
        {
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="move", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class moveRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string origin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string destination;
        
        public moveRequest()
        {
        }
        
        public moveRequest(string origin, string destination)
        {
            this.origin = origin;
            this.destination = destination;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="moveResponse", WrapperNamespace="http://system.server.sirius.org/", IsWrapped=true)]
    public partial class moveResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://system.server.sirius.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool status;
        
        public moveResponse()
        {
        }
        
        public moveResponse(bool status)
        {
            this.status = status;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileOperationsChannel : Sirius.Client.Core.Sys.File.FileOperations, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileOperationsClient : System.ServiceModel.ClientBase<Sirius.Client.Core.Sys.File.FileOperations>, Sirius.Client.Core.Sys.File.FileOperations
    {
        
        public FileOperationsClient()
        {
        }
        
        public FileOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public FileOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public FileOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public FileOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.fileExistsResponse Sirius.Client.Core.Sys.File.FileOperations.fileExists(Sirius.Client.Core.Sys.File.fileExistsRequest request)
        {
            return base.Channel.fileExists(request);
        }
        
        public bool fileExists(string fileName)
        {
            Sirius.Client.Core.Sys.File.fileExistsRequest inValue = new Sirius.Client.Core.Sys.File.fileExistsRequest();
            inValue.fileName = fileName;
            Sirius.Client.Core.Sys.File.fileExistsResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).fileExists(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.copyExResponse Sirius.Client.Core.Sys.File.FileOperations.copyEx(Sirius.Client.Core.Sys.File.copyExRequest request)
        {
            return base.Channel.copyEx(request);
        }
        
        public bool copyEx(string origin, string destination, bool overwrite)
        {
            Sirius.Client.Core.Sys.File.copyExRequest inValue = new Sirius.Client.Core.Sys.File.copyExRequest();
            inValue.origin = origin;
            inValue.destination = destination;
            inValue.overwrite = overwrite;
            Sirius.Client.Core.Sys.File.copyExResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).copyEx(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.createFileResponse Sirius.Client.Core.Sys.File.FileOperations.createFile(Sirius.Client.Core.Sys.File.createFileRequest request)
        {
            return base.Channel.createFile(request);
        }
        
        public bool createFile(string fileName)
        {
            Sirius.Client.Core.Sys.File.createFileRequest inValue = new Sirius.Client.Core.Sys.File.createFileRequest();
            inValue.fileName = fileName;
            Sirius.Client.Core.Sys.File.createFileResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).createFile(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.getFileContentsResponse Sirius.Client.Core.Sys.File.FileOperations.getFileContents(Sirius.Client.Core.Sys.File.getFileContentsRequest request)
        {
            return base.Channel.getFileContents(request);
        }
        
        public string[] getFileContents(string path)
        {
            Sirius.Client.Core.Sys.File.getFileContentsRequest inValue = new Sirius.Client.Core.Sys.File.getFileContentsRequest();
            inValue.path = path;
            Sirius.Client.Core.Sys.File.getFileContentsResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).getFileContents(inValue);
            return retVal.content;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.getFileContentsEx2Response Sirius.Client.Core.Sys.File.FileOperations.getFileContentsEx2(Sirius.Client.Core.Sys.File.getFileContentsEx2Request request)
        {
            return base.Channel.getFileContentsEx2(request);
        }
        
        public string[] getFileContentsEx2(string path, int start, int number)
        {
            Sirius.Client.Core.Sys.File.getFileContentsEx2Request inValue = new Sirius.Client.Core.Sys.File.getFileContentsEx2Request();
            inValue.path = path;
            inValue.start = start;
            inValue.number = number;
            Sirius.Client.Core.Sys.File.getFileContentsEx2Response retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).getFileContentsEx2(inValue);
            return retVal.content;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.getFileContentsExResponse Sirius.Client.Core.Sys.File.FileOperations.getFileContentsEx(Sirius.Client.Core.Sys.File.getFileContentsExRequest request)
        {
            return base.Channel.getFileContentsEx(request);
        }
        
        public string[] getFileContentsEx(string path, int start)
        {
            Sirius.Client.Core.Sys.File.getFileContentsExRequest inValue = new Sirius.Client.Core.Sys.File.getFileContentsExRequest();
            inValue.path = path;
            inValue.start = start;
            Sirius.Client.Core.Sys.File.getFileContentsExResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).getFileContentsEx(inValue);
            return retVal.content;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.appendExResponse Sirius.Client.Core.Sys.File.FileOperations.appendEx(Sirius.Client.Core.Sys.File.appendExRequest request)
        {
            return base.Channel.appendEx(request);
        }
        
        public bool appendEx(string path, string text)
        {
            Sirius.Client.Core.Sys.File.appendExRequest inValue = new Sirius.Client.Core.Sys.File.appendExRequest();
            inValue.path = path;
            inValue.text = text;
            Sirius.Client.Core.Sys.File.appendExResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).appendEx(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.createFileExResponse Sirius.Client.Core.Sys.File.FileOperations.createFileEx(Sirius.Client.Core.Sys.File.createFileExRequest request)
        {
            return base.Channel.createFileEx(request);
        }
        
        public bool createFileEx(string fileName, bool overwrite)
        {
            Sirius.Client.Core.Sys.File.createFileExRequest inValue = new Sirius.Client.Core.Sys.File.createFileExRequest();
            inValue.fileName = fileName;
            inValue.overwrite = overwrite;
            Sirius.Client.Core.Sys.File.createFileExResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).createFileEx(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.deleteFileResponse Sirius.Client.Core.Sys.File.FileOperations.deleteFile(Sirius.Client.Core.Sys.File.deleteFileRequest request)
        {
            return base.Channel.deleteFile(request);
        }
        
        public bool deleteFile(string fileName)
        {
            Sirius.Client.Core.Sys.File.deleteFileRequest inValue = new Sirius.Client.Core.Sys.File.deleteFileRequest();
            inValue.fileName = fileName;
            Sirius.Client.Core.Sys.File.deleteFileResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).deleteFile(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.getAllBytesResponse Sirius.Client.Core.Sys.File.FileOperations.getAllBytes(Sirius.Client.Core.Sys.File.getAllBytesRequest request)
        {
            return base.Channel.getAllBytes(request);
        }
        
        public byte[] getAllBytes(string fileName)
        {
            Sirius.Client.Core.Sys.File.getAllBytesRequest inValue = new Sirius.Client.Core.Sys.File.getAllBytesRequest();
            inValue.fileName = fileName;
            Sirius.Client.Core.Sys.File.getAllBytesResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).getAllBytes(inValue);
            return retVal.content;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.moveExResponse Sirius.Client.Core.Sys.File.FileOperations.moveEx(Sirius.Client.Core.Sys.File.moveExRequest request)
        {
            return base.Channel.moveEx(request);
        }
        
        public bool moveEx(string origin, string destination, bool overwrite)
        {
            Sirius.Client.Core.Sys.File.moveExRequest inValue = new Sirius.Client.Core.Sys.File.moveExRequest();
            inValue.origin = origin;
            inValue.destination = destination;
            inValue.overwrite = overwrite;
            Sirius.Client.Core.Sys.File.moveExResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).moveEx(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.writeExResponse Sirius.Client.Core.Sys.File.FileOperations.writeEx(Sirius.Client.Core.Sys.File.writeExRequest request)
        {
            return base.Channel.writeEx(request);
        }
        
        public bool writeEx(string path, string text)
        {
            Sirius.Client.Core.Sys.File.writeExRequest inValue = new Sirius.Client.Core.Sys.File.writeExRequest();
            inValue.path = path;
            inValue.text = text;
            Sirius.Client.Core.Sys.File.writeExResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).writeEx(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.appendResponse Sirius.Client.Core.Sys.File.FileOperations.append(Sirius.Client.Core.Sys.File.appendRequest request)
        {
            return base.Channel.append(request);
        }
        
        public bool append(string path, byte[] content)
        {
            Sirius.Client.Core.Sys.File.appendRequest inValue = new Sirius.Client.Core.Sys.File.appendRequest();
            inValue.path = path;
            inValue.content = content;
            Sirius.Client.Core.Sys.File.appendResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).append(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.sizeResponse Sirius.Client.Core.Sys.File.FileOperations.size(Sirius.Client.Core.Sys.File.sizeRequest request)
        {
            return base.Channel.size(request);
        }
        
        public long size(string fileName)
        {
            Sirius.Client.Core.Sys.File.sizeRequest inValue = new Sirius.Client.Core.Sys.File.sizeRequest();
            inValue.fileName = fileName;
            Sirius.Client.Core.Sys.File.sizeResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).size(inValue);
            return retVal.fileSize;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.writeResponse Sirius.Client.Core.Sys.File.FileOperations.write(Sirius.Client.Core.Sys.File.writeRequest request)
        {
            return base.Channel.write(request);
        }
        
        public bool write(string path, byte[] content)
        {
            Sirius.Client.Core.Sys.File.writeRequest inValue = new Sirius.Client.Core.Sys.File.writeRequest();
            inValue.path = path;
            inValue.content = content;
            Sirius.Client.Core.Sys.File.writeResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).write(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.copyResponse Sirius.Client.Core.Sys.File.FileOperations.copy(Sirius.Client.Core.Sys.File.copyRequest request)
        {
            return base.Channel.copy(request);
        }
        
        public bool copy(string origin, string destination)
        {
            Sirius.Client.Core.Sys.File.copyRequest inValue = new Sirius.Client.Core.Sys.File.copyRequest();
            inValue.origin = origin;
            inValue.destination = destination;
            Sirius.Client.Core.Sys.File.copyResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).copy(inValue);
            return retVal.status;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.headResponse Sirius.Client.Core.Sys.File.FileOperations.head(Sirius.Client.Core.Sys.File.headRequest request)
        {
            return base.Channel.head(request);
        }
        
        public string[] head(string path, int lines)
        {
            Sirius.Client.Core.Sys.File.headRequest inValue = new Sirius.Client.Core.Sys.File.headRequest();
            inValue.path = path;
            inValue.lines = lines;
            Sirius.Client.Core.Sys.File.headResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).head(inValue);
            return retVal.content;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.tailResponse Sirius.Client.Core.Sys.File.FileOperations.tail(Sirius.Client.Core.Sys.File.tailRequest request)
        {
            return base.Channel.tail(request);
        }
        
        public string[] tail(string path, int lines)
        {
            Sirius.Client.Core.Sys.File.tailRequest inValue = new Sirius.Client.Core.Sys.File.tailRequest();
            inValue.path = path;
            inValue.lines = lines;
            Sirius.Client.Core.Sys.File.tailResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).tail(inValue);
            return retVal.content;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Sirius.Client.Core.Sys.File.moveResponse Sirius.Client.Core.Sys.File.FileOperations.move(Sirius.Client.Core.Sys.File.moveRequest request)
        {
            return base.Channel.move(request);
        }
        
        public bool move(string origin, string destination)
        {
            Sirius.Client.Core.Sys.File.moveRequest inValue = new Sirius.Client.Core.Sys.File.moveRequest();
            inValue.origin = origin;
            inValue.destination = destination;
            Sirius.Client.Core.Sys.File.moveResponse retVal = ((Sirius.Client.Core.Sys.File.FileOperations)(this)).move(inValue);
            return retVal.status;
        }
    }
}
